apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-app-be-staging
  namespace: golf-app-be-staging
spec:
  selector:
    matchLabels:
      app: golf-app-be-staging
  replicas: 1
  template:
    metadata:
      labels:
        app: golf-app-be-staging
    spec:
      containers:
        - name: golf-app-be-staging
          image: git.empatnusabangsa.com/reynerwl2018/golf-app-be:<VERSION>
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: golf-app-be-env
          # volumeMounts:
          #   - name: storage
          #     mountPath: /home/node/uploads
      # volumes:
      #   - name: storage
      #     persistentVolumeClaim:
      #       claimName: gna-be-pvc
      imagePullSecrets:
        - name: regcred
